"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { Alert, Badge, Button, Card } from "@/components/ui";
import { FormattedDocEditor } from "@/components/FormattedDocEditor";
import { FormResponsesPanel } from "@/components/FormResponsesPanel";
import { CompanyEdgePanel } from "@/components/CompanyEdgePanel";
import { AutofillPanel, type AutofillPanelData } from "@/components/AutofillPanel";
import { AutofillHero } from "@/components/AutofillHero";
import { ApplicationGuide } from "@/components/ApplicationGuide";
import { MatchComparison } from "@/components/MatchComparison";
import { RecruiterOutreachPanel } from "@/components/RecruiterOutreachPanel";
import {
  autofillUrlWarning,
  isLikelyMultiStepApply,
  manualApplyNotice,
  multiStepApplyHint,
  requiresAuthentication,
} from "@/lib/apply/detect";
import {
  GUIDE_STEP_ORDER,
  nextStepId,
  type GuideStepId,
} from "@/lib/application-guide";
import { apiFetch } from "@/lib/auth-client";
import { parseUsageError } from "@/lib/billing/format";
import type { BuildIdea, CompanyEdge } from "@/lib/ai";
import { ensureCoverLetterDate } from "@/lib/cover-letter";
import type { MatchScore } from "@/lib/match-score";
import { prepareResumeMarkdown } from "@/lib/markdown";
import { playwrightCaptureEnabled } from "@/lib/playwright-env";
import { ensureAllProfileProjects } from "@/lib/resume-projects";
import type { FormFieldResponse } from "@/lib/types";

export interface TailorWorkflowResult {
  applicationId: string;
  job: {
    title: string;
    company: string;
    location: string;
    description: string;
    url?: string;
    applyUrl?: string;
    atsPlatform?: string;
  };
  tailoredResume: string;
  coverLetter: string;
  matchNotes: string;
  linkedInRecruiterNote?: string;
  recruiterEmail?: string;
  beforeMatch: MatchScore;
  afterMatch: MatchScore;
  edge?: CompanyEdge | null;
}

interface AutofillResult extends AutofillPanelData {
  filledFields: string[];
  skippedFields: string[];
  platform: string;
  log: string[];
}

const STATUS_OPTIONS = [
  "tailored",
  "needs_review",
  "submitted",
  "rejected",
  "interview",
  "offer",
];

function companySlug(company: string): string {
  return (
    company
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "application"
  );
}

/** Post-tailor workflow — same stepper layout as the application detail page. */
export function TailorResultWorkflow({
  result: initial,
}: {
  result: TailorWorkflowResult;
}) {
  const id = initial.applicationId;
  const applyUrl =
    initial.job.applyUrl || initial.job.url || "";
  const atsPlatform = initial.job.atsPlatform || "unknown";

  const [status, setStatusState] = useState("tailored");
  const [resume, setResume] = useState(initial.tailoredResume);
  const [cover, setCover] = useState(
    ensureCoverLetterDate(initial.coverLetter),
  );
  const [linkedInNote, setLinkedInNote] = useState(
    initial.linkedInRecruiterNote ?? "",
  );
  const [recruiterEmail, setRecruiterEmail] = useState(
    initial.recruiterEmail ?? "",
  );
  const [dirty, setDirty] = useState(false);
  const [saving, setSaving] = useState(false);
  const [autofilling, setAutofilling] = useState(false);
  const [showAutofill, setShowAutofill] = useState(false);
  const [autofillResult, setAutofillResult] = useState<AutofillResult | null>(
    null,
  );
  const [shotKey, setShotKey] = useState(0);
  const [reviewScreenshot, setReviewScreenshot] = useState("");
  const [formFields, setFormFields] = useState<FormFieldResponse[]>([]);
  const [formGenerating, setFormGenerating] = useState(false);
  const [edge, setEdge] = useState<CompanyEdge | null>(
    initial.edge ?? null,
  );
  const [incorporating, setIncorporating] = useState(false);
  const [edgeMsg, setEdgeMsg] = useState<string | null>(null);
  const [edgeIncorporated, setEdgeIncorporated] = useState(false);
  const [reapplyingLinks, setReapplyingLinks] = useState(false);
  const [linksMsg, setLinksMsg] = useState<string | null>(null);
  const [pageCapturing, setPageCapturing] = useState(false);
  const formAutoGenerated = useRef(false);
  const pageCaptured = useRef(false);
  const statusSectionRef = useRef<HTMLDivElement>(null);
  const [statusHighlight, setStatusHighlight] = useState(false);
  const [guideStep, setGuideStep] = useState<GuideStepId>("resume");
  const [completedSteps, setCompletedSteps] = useState<Set<GuideStepId>>(
    () => new Set(),
  );

  const generateFormResponses = useCallback(
    async (file?: File) => {
      if (file) {
        const fd = new FormData();
        fd.append("image", file);
        const res = await apiFetch(`/api/applications/${id}/form-responses`, {
          method: "POST",
          body: fd,
        });
        const data = await res.json();
        if (!res.ok)
          throw new Error(data.error ?? "Could not read form fields.");
        setFormFields(data.fields ?? []);
        return data.fields ?? [];
      }
      const res = await apiFetch(`/api/applications/${id}/form-responses`, {
        method: "POST",
      });
      const data = await res.json();
      if (!res.ok)
        throw new Error(data.error ?? "Could not read form fields.");
      setFormFields(data.fields ?? []);
      return data.fields ?? [];
    },
    [id],
  );

  const captureApplyPage = useCallback(async () => {
    setPageCapturing(true);
    try {
      const res = await apiFetch(`/api/applications/${id}/screenshot`, {
        method: "POST",
      });
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error ?? "Could not capture apply page.");
      }
      setShotKey((k) => k + 1);
      const appRes = await apiFetch(`/api/applications/${id}`);
      const data = await appRes.json();
      if (data.reviewScreenshot) setReviewScreenshot(data.reviewScreenshot);
    } finally {
      setPageCapturing(false);
    }
  }, [id]);

  useEffect(() => {
    if (formFields.length > 0 || formAutoGenerated.current) return;
    if (!resume.trim()) return;

    formAutoGenerated.current = true;
    setFormGenerating(true);
    void generateFormResponses()
      .catch(() => {
        formAutoGenerated.current = false;
      })
      .finally(() => {
        setFormGenerating(false);
      });
  }, [formFields.length, generateFormResponses, resume]);

  useEffect(() => {
    if (guideStep !== "apply") return;
    if (!playwrightCaptureEnabled()) return;
    if (reviewScreenshot || pageCaptured.current) return;
    if (!applyUrl) return;

    pageCaptured.current = true;
    void captureApplyPage().catch(() => {
      pageCaptured.current = false;
    });
  }, [guideStep, applyUrl, reviewScreenshot, captureApplyPage]);

  useEffect(() => {
    if (guideStep !== "status" || !statusHighlight) return;
    const frame = requestAnimationFrame(() => {
      statusSectionRef.current?.scrollIntoView({
        behavior: "smooth",
        block: "center",
      });
    });
    return () => cancelAnimationFrame(frame);
  }, [guideStep, statusHighlight]);

  async function addBuildIdeas(ideas: BuildIdea[]) {
    if (ideas.length === 0) return;
    setIncorporating(true);
    setEdgeMsg(null);
    try {
      const res = await apiFetch(`/api/applications/${id}/incorporate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ ideas }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(parseUsageError(data));
      setResume(data.resume ?? resume);
      setCover(ensureCoverLetterDate(data.coverLetter ?? cover));
      setDirty(false);
      setEdgeMsg(`Added ${ideas.length} to your resume & cover letter ✓`);
      setEdgeIncorporated(true);
    } catch (e) {
      setEdgeMsg((e as Error).message);
    } finally {
      setIncorporating(false);
    }
  }

  async function saveDocs() {
    setSaving(true);
    const datedCover = ensureCoverLetterDate(cover);
    if (datedCover !== cover) setCover(datedCover);
    await apiFetch(`/api/applications/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        tailoredResume: resume,
        coverLetter: datedCover,
        linkedInRecruiterNote: linkedInNote,
        recruiterEmail,
      }),
    });
    setSaving(false);
    setDirty(false);
  }

  async function reapplyLinks() {
    if (!resume.trim()) return;
    setReapplyingLinks(true);
    setLinksMsg(null);
    try {
      const res = await apiFetch("/api/profile");
      const profile = await res.json();
      if (!res.ok) {
        throw new Error(profile.error ?? "Could not load profile.");
      }
      let updated = ensureAllProfileProjects(resume, profile.projects ?? []);
      updated = prepareResumeMarkdown(updated, profile.projects ?? [], {
        fullName: profile.fullName,
        email: profile.email,
        phone: profile.phone,
        location: profile.location,
        linkedin: profile.linkedin,
        github: profile.github,
        website: profile.website,
      });
      setResume(updated);
      setSaving(true);
      await apiFetch(`/api/applications/${id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          tailoredResume: updated,
          coverLetter: cover,
        }),
      });
      setDirty(false);
      setLinksMsg("Contact and project links updated from your profile ✓");
      setTimeout(() => setLinksMsg(null), 5000);
    } catch (e) {
      setLinksMsg((e as Error).message);
    } finally {
      setReapplyingLinks(false);
      setSaving(false);
    }
  }

  function scrollToStatusUpdate() {
    setGuideStep("status");
    setStatusHighlight(true);
  }

  function goToGuideStep(step: GuideStepId) {
    if (step === "status") {
      scrollToStatusUpdate();
      return;
    }
    setStatusHighlight(false);
    setGuideStep(step);
  }

  async function advanceGuide() {
    if (
      dirty &&
      (guideStep === "resume" ||
        guideStep === "cover" ||
        guideStep === "outreach")
    ) {
      await saveDocs();
    }

    setCompletedSteps((prev) => new Set(prev).add(guideStep));

    const next = nextStepId(guideStep);
    if (!next) {
      return;
    }
    if (guideStep !== "status" && next === "status") {
      scrollToStatusUpdate();
      return;
    }

    goToGuideStep(next);
  }

  function skipGuideStep() {
    setCompletedSteps((prev) => new Set(prev).add(guideStep));
    const next = nextStepId(guideStep);
    if (next) goToGuideStep(next);
  }

  async function setStatus(next: string) {
    await apiFetch(`/api/applications/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ status: next }),
    });
    setStatusState(next);
    setStatusHighlight(false);
    if (next === "submitted" || next === "interview" || next === "offer") {
      setCompletedSteps((prev) => {
        const all = new Set(prev);
        for (const s of GUIDE_STEP_ORDER) all.add(s);
        return all;
      });
      setGuideStep("status");
    }
  }

  async function autofill(headless: boolean, continueSession = false) {
    if (dirty) await saveDocs();
    setAutofilling(true);
    setShowAutofill(true);
    if (!continueSession) setAutofillResult(null);
    try {
      const res = await apiFetch(`/api/applications/${id}/autofill`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          headless,
          continueSession,
          resumeAlreadyUploaded: continueSession
            ? autofillResult?.uploadedResume
            : false,
        }),
      });
      const data = (await res.json()) as AutofillResult;
      if (!res.ok) {
        const errMsg = parseUsageError(
          data as { error?: string; code?: string },
        );
        const base =
          continueSession && autofillResult
            ? autofillResult
            : {
                fields: [] as AutofillResult["fields"],
                requiredFilled: 0,
                requiredTotal: 0,
                optionalFilled: 0,
                optionalTotal: 0,
                passes: 0,
                uploadedResume: false,
                filledFields: [] as string[],
                skippedFields: [] as string[],
                platform: "",
                log: [] as string[],
              };
        setAutofillResult({
          ...base,
          ok: false,
          error:
            res.status === 402
              ? `${errMsg} Visit Billing to add credits.`
              : errMsg,
        });
        return;
      }
      setAutofillResult((prev) => {
        if (!continueSession || !prev) return data;
        const byLabel = new Map(
          prev.fields.map((f) => [f.label.slice(0, 80), f]),
        );
        for (const f of data.fields) {
          byLabel.set(f.label.slice(0, 80), f);
        }
        return {
          ...data,
          fields: Array.from(byLabel.values()),
          requiredFilled: Math.max(data.requiredFilled, prev.requiredFilled),
          uploadedResume: data.uploadedResume || prev.uploadedResume,
        };
      });
      setShotKey((k) => k + 1);
      if (data.ok) {
        setCompletedSteps((prev) => new Set(prev).add("apply"));
        setGuideStep("apply");
      }
    } finally {
      setAutofilling(false);
    }
  }

  const noApplyUrl = !applyUrl.trim();
  const manualApply =
    noApplyUrl || requiresAuthentication(applyUrl, atsPlatform);
  const multiStepApply = isLikelyMultiStepApply(applyUrl);
  const applyWarning =
    noApplyUrl || manualApply ? null : autofillUrlWarning(applyUrl);
  const slug = companySlug(initial.job.company);

  const autofillComplete = Boolean(
    autofillResult &&
      autofillResult.requiredFilled >= autofillResult.requiredTotal &&
      autofillResult.requiredTotal > 0,
  );
  const guideContext = {
    manualApply,
    hasEdge: Boolean(edge),
    edgeBuildCount: edge?.build.length ?? 0,
    edgeIncorporated,
    autofillComplete,
    formFieldsCount: formFields.length,
    statusSubmitted: ["submitted", "interview", "offer"].includes(status),
    multiStepApply: multiStepApply || Boolean(autofillResult?.multiStep),
    autofillInProgress:
      autofilling ||
      Boolean(showAutofill && autofillResult && !autofillComplete),
  };

  const disabledReason = noApplyUrl
    ? "Add a job link when tailoring so we can open the apply page — or copy form answers below."
    : requiresAuthentication(applyUrl, atsPlatform)
      ? "This job needs sign-in — open the apply page and paste answers manually."
      : null;

  return (
    <div className="space-y-6">
      <header className="space-y-4">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div className="min-w-0 flex-1">
            <h2 className="text-xl font-bold tracking-tight text-slate-900 sm:text-2xl">
              {initial.job.title || "Tailored documents"}
            </h2>
            <p className="mt-1 text-sm text-slate-500">
              {[initial.job.company, initial.job.location]
                .filter(Boolean)
                .join(" · ")}
              {applyUrl ? (
                <>
                  {" · "}
                  <a
                    href={applyUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="text-emerald-600 hover:underline"
                  >
                    View posting
                  </a>
                </>
              ) : null}
              {" · "}
              <Link
                href={`/applications/${id}`}
                className="text-emerald-600 hover:underline"
              >
                Open in Applications
              </Link>
            </p>
          </div>
          <Badge status={status} />
        </div>

        {initial.beforeMatch && initial.afterMatch && (
          <MatchComparison
            before={initial.beforeMatch}
            after={initial.afterMatch}
          />
        )}
      </header>

      <ApplicationGuide
        currentStep={guideStep}
        completedSteps={completedSteps}
        context={guideContext}
        dirty={dirty}
        saving={saving}
        stepCounts={{
          edge: edge?.build.length ?? 0,
          apply: formFields.length,
        }}
        onGoToStep={goToGuideStep}
        onNext={advanceGuide}
        onSkip={skipGuideStep}
        onSave={() => void saveDocs()}
      />

      {guideStep !== "status" && (
        <Card>
          {guideStep === "apply" ? (
            <div className="space-y-6">
              <AutofillHero
                busy={autofilling}
                disabled={manualApply}
                disabledReason={disabledReason}
                onAutofill={() => autofill(false)}
                onPreview={() => autofill(true)}
                applyUrl={applyUrl || null}
              />

              {(showAutofill || autofilling || autofillResult) &&
                !manualApply && (
                  <AutofillPanel
                    data={autofillResult}
                    loading={autofilling}
                    onContinue={() => autofill(false, true)}
                    onComplete={scrollToStatusUpdate}
                    onClose={() => setShowAutofill(false)}
                  />
                )}

              <div>
                <div className="mb-3">
                  <h3 className="text-sm font-semibold text-slate-900">
                    Form answers backup
                  </h3>
                  <p className="mt-0.5 text-sm text-slate-500">
                    Copy-paste helpers if auto-fill can&apos;t reach every
                    field.
                  </p>
                </div>
                <FormResponsesPanel
                  embedded
                  screenshotUrl={
                    reviewScreenshot
                      ? `/api/applications/${id}/screenshot?v=${shotKey}`
                      : null
                  }
                  applyPageUrl={applyUrl || null}
                  pageCaptureLoading={pageCapturing}
                  initialFields={formFields}
                  allowUpload
                  allowGenerateWithoutScreenshot
                  externalLoading={formGenerating}
                  resumeMarkdown={resume}
                  coverMarkdown={cover}
                  downloadSlug={slug}
                  companyName={initial.job.company}
                  onGenerate={generateFormResponses}
                />
              </div>
            </div>
          ) : guideStep === "edge" ? (
            edge ? (
              <CompanyEdgePanel
                edge={edge}
                company={initial.job.company}
                onAdd={addBuildIdeas}
                adding={incorporating}
                addedMsg={edgeMsg}
              />
            ) : (
              <p className="py-12 text-center text-sm text-slate-500">
                Company research isn&apos;t available for this role.
              </p>
            )
          ) : guideStep === "outreach" ? (
            <RecruiterOutreachPanel
              embedded
              jobTitle={initial.job.title}
              company={initial.job.company}
              linkedInNote={linkedInNote}
              recruiterEmail={recruiterEmail}
              onLinkedInChange={(v) => {
                setLinkedInNote(v);
                setDirty(true);
              }}
              onEmailChange={(v) => {
                setRecruiterEmail(v);
                setDirty(true);
              }}
            />
          ) : (
            <FormattedDocEditor
              label={
                guideStep === "resume" ? "Tailored resume" : "Cover letter"
              }
              showLabel={false}
              hideTextDownloads
              value={guideStep === "resume" ? resume : cover}
              onChange={(v) => {
                if (guideStep === "resume") setResume(v);
                else setCover(v);
                setDirty(true);
              }}
              kind={guideStep === "resume" ? "resume" : "cover"}
              downloadSlug={slug}
              pdfTitle={
                guideStep === "resume"
                  ? `Resume — ${initial.job.company}`
                  : `Cover letter — ${initial.job.company}`
              }
              minHeight={guideStep === "resume" ? 480 : 420}
            />
          )}

          {(guideStep === "resume" || guideStep === "cover") && (
            <div className="mt-4 flex flex-wrap items-center gap-3 border-t border-slate-100 pt-4">
              <Button
                onClick={saveDocs}
                disabled={saving || !dirty}
                size="sm"
              >
                {saving ? "Saving…" : dirty ? "Save edits" : "Saved"}
              </Button>
              {guideStep === "resume" && resume.trim() && (
                <Button
                  variant="secondary"
                  size="sm"
                  onClick={() => void reapplyLinks()}
                  disabled={reapplyingLinks || saving}
                  title="Refresh LinkedIn, GitHub, portfolio, and project links from your profile"
                >
                  {reapplyingLinks ? "Updating links…" : "Re-apply links"}
                </Button>
              )}
              {linksMsg && (
                <span
                  className={`text-sm ${
                    linksMsg.includes("✓")
                      ? "text-emerald-600"
                      : "text-red-600"
                  }`}
                >
                  {linksMsg}
                </span>
              )}
            </div>
          )}
        </Card>
      )}

      {manualApply && applyUrl && (
        <Alert variant="info">
          {manualApplyNotice(applyUrl, atsPlatform)}
        </Alert>
      )}

      {noApplyUrl && guideStep === "apply" && (
        <Alert variant="info">
          No apply link on this run — use form answers below, or re-tailor with
          a job URL to enable auto-fill.
        </Alert>
      )}

      {applyWarning && <Alert variant="warning">{applyWarning}</Alert>}

      {multiStepApply && !manualApply && guideStep === "apply" && (
        <Alert variant="info">{multiStepApplyHint(applyUrl)}</Alert>
      )}

      {guideStep === "status" && (
        <div
          ref={statusSectionRef}
          id="update-status"
          className={`scroll-mt-24 transition-shadow duration-500 ${
            statusHighlight
              ? "rounded-2xl ring-2 ring-emerald-500 ring-offset-2"
              : ""
          }`}
        >
          <Card>
            <h2 className="mb-1 text-lg font-semibold">Update status</h2>
            {statusHighlight && (
              <p className="mb-3 text-sm text-emerald-700">
                Choose a status — e.g. <strong>submitted</strong> after you
                submit the application in the browser.
              </p>
            )}
            <div className="flex flex-wrap gap-2">
              {STATUS_OPTIONS.map((s) => (
                <Button
                  key={s}
                  variant={status === s ? "primary" : "secondary"}
                  onClick={() => setStatus(s)}
                >
                  {s.replace(/_/g, " ")}
                </Button>
              ))}
            </div>
          </Card>
        </div>
      )}
    </div>
  );
}
