"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useParams, useSearchParams } from "next/navigation";
import Link from "next/link";
import { Badge, Button, Card, Alert } from "@/components/ui";
import { FormattedDocEditor } from "@/components/FormattedDocEditor";
import { FormResponsesPanel } from "@/components/FormResponsesPanel";
import { CompanyEdgePanel } from "@/components/CompanyEdgePanel";
import { AutofillPanel, type AutofillPanelData } from "@/components/AutofillPanel";
import { AutofillHero } from "@/components/AutofillHero";
import { ApplicationGuide } from "@/components/ApplicationGuide";
import { MatchComparison } from "@/components/MatchComparison";
import { RecruiterOutreachPanel } from "@/components/RecruiterOutreachPanel";
import { autofillUrlWarning, manualApplyNotice, requiresAuthentication, isLikelyMultiStepApply, multiStepApplyHint } from "@/lib/apply/detect";
import {
  GUIDE_STEP_ORDER,
  nextStepId,
  type GuideStepId,
} from "@/lib/application-guide";
import { apiFetch } from "@/lib/auth-client";
import { parseUsageError } from "@/lib/billing/format";
import type { BuildIdea, CompanyEdge } from "@/lib/ai";
import { normalizeCompanyEdge } from "@/lib/ai";
import type { MatchScore } from "@/lib/match-score";
import type { FormFieldResponse } from "@/lib/types";
import { prepareResumeMarkdown } from "@/lib/markdown";
import { ensureCoverLetterDate } from "@/lib/cover-letter";
import { playwrightCaptureEnabled } from "@/lib/playwright-env";
import { ensureAllProfileProjects } from "@/lib/resume-projects";
import { safeJson } from "@/lib/util";

interface ApplicationDetail {
  id: string;
  status: string;
  tailoredResume: string;
  coverLetter: string;
  matchNotes: string;
  linkedInRecruiterNote?: string;
  recruiterEmail?: string;
  beforeMatch?: string;
  afterMatch?: string;
  companyEdge?: string;
  autoApplyLog: string;
  reviewScreenshot: string;
  job: {
    id: string;
    title: string;
    company: string;
    location: string;
    url: string;
    applyUrl: string;
    atsPlatform: string;
    description: string;
  };
}

interface AutofillResult extends AutofillPanelData {
  filledFields: string[];
  skippedFields: string[];
  platform: string;
  log: string[];
}

const STATUS_OPTIONS = [
  "tailored",
  "needs_review",
  "submitted",
  "rejected",
  "interview",
  "offer",
];

function companySlug(company: string): string {
  return company.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "application";
}

export default function ApplicationDetailPage() {
  const params = useParams<{ id: string }>();
  const searchParams = useSearchParams();
  const id = params.id;

  const [app, setApp] = useState<ApplicationDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [resume, setResume] = useState("");
  const [cover, setCover] = useState("");
  const [linkedInNote, setLinkedInNote] = useState("");
  const [recruiterEmail, setRecruiterEmail] = useState("");
  const [dirty, setDirty] = useState(false);
  const [saving, setSaving] = useState(false);
  const [autofilling, setAutofilling] = useState(false);
  const [showAutofill, setShowAutofill] = useState(false);
  const [result, setResult] = useState<AutofillResult | null>(null);
  const [shotKey, setShotKey] = useState(0);
  const [formFields, setFormFields] = useState<FormFieldResponse[]>([]);
  const [beforeMatch, setBeforeMatch] = useState<MatchScore | null>(null);
  const [afterMatch, setAfterMatch] = useState<MatchScore | null>(null);
  const [matchLoading, setMatchLoading] = useState(false);
  const [matchError, setMatchError] = useState<string | null>(null);
  const [formGenerating, setFormGenerating] = useState(false);
  const [pageCapturing, setPageCapturing] = useState(false);
  const [edge, setEdge] = useState<CompanyEdge | null>(null);
  const [edgeLoading, setEdgeLoading] = useState(false);
  const [incorporating, setIncorporating] = useState(false);
  const [edgeMsg, setEdgeMsg] = useState<string | null>(null);
  const formAutoGenerated = useRef(false);
  const pageCaptured = useRef(false);
  const statusSectionRef = useRef<HTMLDivElement>(null);
  const [statusHighlight, setStatusHighlight] = useState(false);
  const [guideStep, setGuideStep] = useState<GuideStepId>("resume");
  const [completedSteps, setCompletedSteps] = useState<Set<GuideStepId>>(
    () => new Set(),
  );
  const [edgeIncorporated, setEdgeIncorporated] = useState(false);
  const [reapplyingLinks, setReapplyingLinks] = useState(false);
  const [linksMsg, setLinksMsg] = useState<string | null>(null);

  function parseMatch(raw?: string): MatchScore | null {
    if (!raw?.trim()) return null;
    const parsed = safeJson<MatchScore | null>(raw, null);
    return parsed && typeof parsed.score === "number" ? parsed : null;
  }

  function parseEdge(raw?: string): CompanyEdge | null {
    if (!raw?.trim()) return null;
    const parsed = safeJson<CompanyEdge | null>(raw, null);
    if (!parsed || !Array.isArray(parsed.research)) return null;
    return normalizeCompanyEdge(parsed);
  }

  const generateFormResponses = useCallback(
    async (file?: File) => {
      if (file) {
        const fd = new FormData();
        fd.append("image", file);
        const res = await apiFetch(
          `/api/applications/${id}/form-responses`,
          { method: "POST", body: fd },
        );
        const data = await res.json();
        if (!res.ok)
          throw new Error(data.error ?? "Could not read form fields.");
        setFormFields(data.fields ?? []);
        return data.fields ?? [];
      }
      const res = await apiFetch(
        `/api/applications/${id}/form-responses`,
        { method: "POST" },
      );
      const data = await res.json();
      if (!res.ok)
        throw new Error(data.error ?? "Could not read form fields.");
      setFormFields(data.fields ?? []);
      return data.fields ?? [];
    },
    [id],
  );

  const captureApplyPage = useCallback(async () => {
    setPageCapturing(true);
    try {
      const res = await apiFetch(`/api/applications/${id}/screenshot`, {
        method: "POST",
      });
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error ?? "Could not capture apply page.");
      }
      setShotKey((k) => k + 1);
      const appRes = await apiFetch(`/api/applications/${id}`);
      const data = await appRes.json();
      setApp(data);
    } finally {
      setPageCapturing(false);
    }
  }, [id]);

  const load = useCallback(async () => {
    const res = await apiFetch(`/api/applications/${id}`);
    const data = await res.json();
    setApp(data);
    setResume(data.tailoredResume ?? "");
    setCover(ensureCoverLetterDate(data.coverLetter ?? ""));
    setLinkedInNote(data.linkedInRecruiterNote ?? "");
    setRecruiterEmail(data.recruiterEmail ?? "");
    const stored = safeJson<Record<string, unknown>>(data.formAnswers, {});
    setFormFields((stored.generatedFields as FormFieldResponse[]) ?? []);
    const cachedEdge = parseEdge(data.companyEdge);
    if (cachedEdge) setEdge(cachedEdge);
    setLoading(false);
  }, [id]);

  useEffect(() => {
    if (!app || loading) return;

    const cachedBefore = parseMatch(app.beforeMatch);
    const cachedAfter = parseMatch(app.afterMatch);
    if (cachedBefore && cachedAfter) {
      setBeforeMatch(cachedBefore);
      setAfterMatch(cachedAfter);
      return;
    }
    if (!app.tailoredResume?.trim()) return;

    let cancelled = false;
    setMatchLoading(true);
    setMatchError(null);
    void (async () => {
      try {
        const res = await apiFetch(`/api/applications/${app.id}/match-scores`);
        const scores = await res.json();
        if (cancelled) return;
        if (res.ok && scores.beforeMatch && scores.afterMatch) {
          setBeforeMatch(scores.beforeMatch);
          setAfterMatch(scores.afterMatch);
        } else {
          setMatchError(scores.error ?? "Could not load ATS match scores.");
        }
      } catch {
        if (!cancelled) setMatchError("Could not load ATS match scores.");
      } finally {
        if (!cancelled) setMatchLoading(false);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [app, loading]);

  useEffect(() => {
    if (!app || loading || edge) return;

    const cached = parseEdge(app.companyEdge);
    if (cached) {
      setEdge(cached);
      return;
    }

    let cancelled = false;
    setEdgeLoading(true);
    void (async () => {
      try {
        const res = await apiFetch(`/api/applications/${app.id}/edge`);
        const data = await res.json();
        if (!cancelled && res.ok && data.edge) {
          setEdge(normalizeCompanyEdge(data.edge));
        }
      } finally {
        if (!cancelled) setEdgeLoading(false);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [app, loading, edge]);

  useEffect(() => {
    load();
  }, [load]);

  useEffect(() => {
    const tab = searchParams.get("tab");
    if (tab === "form") setGuideStep("apply");
    else if (tab === "edge") setGuideStep("edge");
    else if (tab === "cover") setGuideStep("cover");
    else if (tab === "resume") setGuideStep("resume");
  }, [searchParams]);

  useEffect(() => {
    if (!app || loading) return;
    if (formFields.length > 0 || formAutoGenerated.current) return;
    if (!app.tailoredResume?.trim()) return;

    const applyUrl = app.job.applyUrl || app.job.url;
    const manual = requiresAuthentication(applyUrl, app.job.atsPlatform);
    const openFormTab =
      manual || searchParams.get("tab") === "form";
    if (!openFormTab) return;

    formAutoGenerated.current = true;
    setGuideStep("apply");
    setFormGenerating(true);
    void generateFormResponses()
      .catch(() => {
        formAutoGenerated.current = false;
      })
      .finally(() => {
        setFormGenerating(false);
      });
  }, [app, loading, formFields.length, searchParams, generateFormResponses]);

  useEffect(() => {
    if (!app || loading || guideStep !== "apply") return;
    if (!playwrightCaptureEnabled()) return;
    if (app.reviewScreenshot || pageCaptured.current) return;

    const applyUrl = app.job.applyUrl || app.job.url;
    if (!applyUrl) return;

    pageCaptured.current = true;
    void captureApplyPage().catch(() => {
      pageCaptured.current = false;
    });
  }, [app, loading, guideStep, captureApplyPage]);

  async function addBuildIdeas(ideas: BuildIdea[]) {
    if (ideas.length === 0) return;
    setIncorporating(true);
    setEdgeMsg(null);
    try {
      const res = await apiFetch(`/api/applications/${id}/incorporate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ ideas }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(parseUsageError(data));
      setResume(data.resume ?? resume);
      setCover(ensureCoverLetterDate(data.coverLetter ?? cover));
      setDirty(false);
      setEdgeMsg(
        `Added ${ideas.length} to your resume & cover letter ✓`,
      );
      setEdgeIncorporated(true);
    } catch (e) {
      setEdgeMsg((e as Error).message);
    } finally {
      setIncorporating(false);
    }
  }

  async function saveDocs() {
    setSaving(true);
    const datedCover = ensureCoverLetterDate(cover);
    if (datedCover !== cover) setCover(datedCover);
    await apiFetch(`/api/applications/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        tailoredResume: resume,
        coverLetter: datedCover,
        linkedInRecruiterNote: linkedInNote,
        recruiterEmail,
      }),
    });
    setSaving(false);
    setDirty(false);
  }

  async function reapplyLinks() {
    if (!resume.trim()) return;
    setReapplyingLinks(true);
    setLinksMsg(null);
    try {
      const res = await apiFetch("/api/profile");
      const profile = await res.json();
      if (!res.ok) {
        throw new Error(profile.error ?? "Could not load profile.");
      }
      let updated = ensureAllProfileProjects(
        resume,
        profile.projects ?? [],
      );
      updated = prepareResumeMarkdown(
        updated,
        profile.projects ?? [],
        {
          email: profile.email,
          phone: profile.phone,
          location: profile.location,
          linkedin: profile.linkedin,
          github: profile.github,
          website: profile.website,
        },
      );
      setResume(updated);
      setSaving(true);
      await apiFetch(`/api/applications/${id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          tailoredResume: updated,
          coverLetter: cover,
        }),
      });
      setDirty(false);
      setLinksMsg("Contact and project links updated from your profile ✓");
      setTimeout(() => setLinksMsg(null), 5000);
    } catch (e) {
      setLinksMsg((e as Error).message);
    } finally {
      setReapplyingLinks(false);
      setSaving(false);
    }
  }

  function goToGuideStep(step: GuideStepId) {
    if (step === "status") {
      scrollToStatusUpdate();
      return;
    }
    setStatusHighlight(false);
    setGuideStep(step);
  }

  async function advanceGuide() {
    if (
      dirty &&
      (guideStep === "resume" ||
        guideStep === "cover" ||
        guideStep === "outreach")
    ) {
      await saveDocs();
    }

    setCompletedSteps((prev) => new Set(prev).add(guideStep));

    const next = nextStepId(guideStep);
    if (!next) {
      return;
    }
    if (guideStep !== "status" && next === "status") {
      scrollToStatusUpdate();
      return;
    }

    goToGuideStep(next);
  }

  function skipGuideStep() {
    setCompletedSteps((prev) => new Set(prev).add(guideStep));
    const next = nextStepId(guideStep);
    if (next) goToGuideStep(next);
  }

  async function setStatus(status: string) {
    await apiFetch(`/api/applications/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ status }),
    });
    setStatusHighlight(false);
    if (status === "submitted" || status === "interview" || status === "offer") {
      setCompletedSteps((prev) => {
        const next = new Set(prev);
        for (const s of GUIDE_STEP_ORDER) next.add(s);
        return next;
      });
      setGuideStep("status");
    }
    load();
  }

  function scrollToStatusUpdate() {
    setGuideStep("status");
    setStatusHighlight(true);
  }

  useEffect(() => {
    if (guideStep !== "status" || !statusHighlight) return;
    const frame = requestAnimationFrame(() => {
      statusSectionRef.current?.scrollIntoView({
        behavior: "smooth",
        block: "center",
      });
    });
    return () => cancelAnimationFrame(frame);
  }, [guideStep, statusHighlight]);

  async function autofill(headless: boolean, continueSession = false) {
    // Open in the user's browser immediately (before any await) so popup blockers
    // allow it. Server-side headed Chrome only works on a local Mac; on Railway
    // this is how the application tab appears for review/submit.
    const applyLink = app?.job.applyUrl || app?.job.url || "";
    if (applyLink && !headless) {
      window.open(applyLink, "_blank", "noopener,noreferrer");
    }

    if (dirty) await saveDocs();
    setAutofilling(true);
    setShowAutofill(true);
    if (!continueSession) setResult(null);
    try {
      const res = await apiFetch(`/api/applications/${id}/autofill`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          headless,
          continueSession,
          resumeAlreadyUploaded: continueSession ? result?.uploadedResume : false,
        }),
      });
      const data = (await res.json()) as AutofillResult;
      if (!res.ok) {
        const errMsg = parseUsageError(data as { error?: string; code?: string });
        const base = continueSession && result ? result : {
          fields: [] as AutofillResult["fields"],
          requiredFilled: 0,
          requiredTotal: 0,
          optionalFilled: 0,
          optionalTotal: 0,
          passes: 0,
          uploadedResume: false,
          filledFields: [] as string[],
          skippedFields: [] as string[],
          platform: "",
          log: [] as string[],
        };
        setResult({
          ...base,
          ok: false,
          error:
            res.status === 402
              ? `${errMsg} Visit Billing to add credits.`
              : errMsg,
        });
        return;
      }
      setResult((prev) => {
        if (!continueSession || !prev) return data;
        const byLabel = new Map(prev.fields.map((f) => [f.label.slice(0, 80), f]));
        for (const f of data.fields) {
          byLabel.set(f.label.slice(0, 80), f);
        }
        return {
          ...data,
          fields: Array.from(byLabel.values()),
          requiredFilled: Math.max(data.requiredFilled, prev.requiredFilled),
          uploadedResume: data.uploadedResume || prev.uploadedResume,
        };
      });
      setShotKey((k) => k + 1);
      await load();
      if (data.ok) {
        setCompletedSteps((prev) => new Set(prev).add("apply"));
        setGuideStep("apply");
      }
    } finally {
      setAutofilling(false);
    }
  }

  if (loading) return <p className="text-slate-500">Loading…</p>;
  if (!app) return <p className="text-slate-500">Application not found.</p>;

  const applyUrl = app.job.applyUrl || app.job.url;
  const manualApply = requiresAuthentication(applyUrl, app.job.atsPlatform);
  const multiStepApply = isLikelyMultiStepApply(applyUrl);
  const applyWarning = manualApply ? null : autofillUrlWarning(applyUrl);
  const slug = companySlug(app.job.company);

  const autofillComplete = Boolean(
    result &&
      result.requiredFilled >= result.requiredTotal &&
      result.requiredTotal > 0,
  );
  const guideContext = {
    manualApply,
    hasEdge: Boolean(edge),
    edgeBuildCount: edge?.build.length ?? 0,
    edgeIncorporated,
    autofillComplete,
    formFieldsCount: formFields.length,
    statusSubmitted: ["submitted", "interview", "offer"].includes(app.status),
    multiStepApply: multiStepApply || Boolean(result?.multiStep),
    autofillInProgress: autofilling || Boolean(showAutofill && result && !autofillComplete),
  };

  return (
    <div className="space-y-6">
      <Link
        href="/applications"
        className="inline-flex text-sm font-medium text-emerald-600 hover:underline"
      >
        ← All Applications
      </Link>

      <header className="space-y-4">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div className="min-w-0 flex-1">
            <h1 className="text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">
              {app.job.title}
            </h1>
            <p className="mt-1.5 text-sm text-slate-500">
              {[app.job.company, app.job.location].filter(Boolean).join(" · ")}
              {" · "}
              <a
                href={app.job.url}
                target="_blank"
                rel="noreferrer"
                className="text-emerald-600 hover:underline"
              >
                View posting
              </a>
            </p>
          </div>
          <Badge status={app.status} />
        </div>

        {matchLoading && !beforeMatch && (
          <p className="text-sm text-slate-500">Scoring ATS keyword match…</p>
        )}
        {matchError && !beforeMatch && (
          <Alert variant="warning">{matchError}</Alert>
        )}
        {beforeMatch && afterMatch && (
          <MatchComparison before={beforeMatch} after={afterMatch} />
        )}
      </header>

      <ApplicationGuide
        currentStep={guideStep}
        completedSteps={completedSteps}
        context={guideContext}
        dirty={dirty}
        saving={saving}
        stepCounts={{
          edge: edge?.build.length ?? 0,
          apply: formFields.length,
        }}
        onGoToStep={goToGuideStep}
        onNext={advanceGuide}
        onSkip={skipGuideStep}
        onSave={() => void saveDocs()}
      />

      {guideStep !== "status" && (
      <Card>
        {guideStep === "apply" ? (
          <div className="space-y-6">
            <AutofillHero
              busy={autofilling}
              disabled={manualApply}
              disabledReason={
                manualApply
                  ? "This job needs sign-in — open the apply page and paste answers manually."
                  : null
              }
              onAutofill={() => autofill(false)}
              onPreview={() => autofill(true)}
              applyUrl={applyUrl}
            />

            {(showAutofill || autofilling || result) && !manualApply && (
              <AutofillPanel
                data={result}
                loading={autofilling}
                onContinue={() => autofill(false, true)}
                onComplete={scrollToStatusUpdate}
                onClose={() => setShowAutofill(false)}
              />
            )}

            <div>
              <div className="mb-3">
                <h3 className="text-sm font-semibold text-slate-900">
                  Form answers backup
                </h3>
                <p className="mt-0.5 text-sm text-slate-500">
                  Copy-paste helpers if auto-fill can&apos;t reach every field.
                </p>
              </div>
              <FormResponsesPanel
                embedded
                screenshotUrl={
                  app.reviewScreenshot
                    ? `/api/applications/${id}/screenshot?v=${shotKey}`
                    : null
                }
                applyPageUrl={applyUrl}
                pageCaptureLoading={pageCapturing}
                initialFields={formFields}
                allowUpload
                externalLoading={formGenerating}
                resumeMarkdown={resume}
                coverMarkdown={cover}
                downloadSlug={slug}
                companyName={app.job.company}
                onGenerate={generateFormResponses}
              />
            </div>
          </div>
        ) : guideStep === "edge" ? (
          edgeLoading && !edge ? (
            <p className="py-12 text-center text-sm text-slate-500">
              Researching your edge at {app.job.company}…
            </p>
          ) : edge ? (
            <CompanyEdgePanel
              edge={edge}
              company={app.job.company}
              onAdd={addBuildIdeas}
              adding={incorporating}
              addedMsg={edgeMsg}
            />
          ) : (
            <p className="py-12 text-center text-sm text-slate-500">
              Company research isn&apos;t available for this application yet.
            </p>
          )
        ) : guideStep === "outreach" ? (
          <RecruiterOutreachPanel
            embedded
            jobTitle={app.job.title}
            company={app.job.company}
            linkedInNote={linkedInNote}
            recruiterEmail={recruiterEmail}
            onLinkedInChange={(v) => {
              setLinkedInNote(v);
              setDirty(true);
            }}
            onEmailChange={(v) => {
              setRecruiterEmail(v);
              setDirty(true);
            }}
          />
        ) : (
          <FormattedDocEditor
            label={guideStep === "resume" ? "Tailored resume" : "Cover letter"}
            showLabel={false}
            hideTextDownloads
            value={guideStep === "resume" ? resume : cover}
            onChange={(v) => {
              if (guideStep === "resume") setResume(v);
              else setCover(v);
              setDirty(true);
            }}
            kind={guideStep === "resume" ? "resume" : "cover"}
            downloadSlug={slug}
            pdfTitle={
              guideStep === "resume"
                ? `Resume — ${app.job.company}`
                : `Cover letter — ${app.job.company}`
            }
            minHeight={guideStep === "resume" ? 480 : 420}
          />
        )}

        {(guideStep === "resume" || guideStep === "cover") && (
          <div className="mt-4 flex flex-wrap items-center gap-3 border-t border-slate-100 pt-4">
            <Button
              onClick={saveDocs}
              disabled={saving || !dirty}
              size="sm"
            >
              {saving ? "Saving…" : dirty ? "Save edits" : "Saved"}
            </Button>
            {guideStep === "resume" && resume.trim() && (
              <Button
                variant="secondary"
                size="sm"
                onClick={() => void reapplyLinks()}
                disabled={reapplyingLinks || saving}
                title="Refresh LinkedIn, GitHub, portfolio, and project links from your profile"
              >
                {reapplyingLinks ? "Updating links…" : "Re-apply links"}
              </Button>
            )}
            {linksMsg && (
              <span
                className={`text-sm ${
                  linksMsg.includes("✓") ? "text-emerald-600" : "text-red-600"
                }`}
              >
                {linksMsg}
              </span>
            )}
          </div>
        )}
      </Card>
      )}

      {manualApply && (
        <Alert variant="info">
          {manualApplyNotice(applyUrl, app.job.atsPlatform)}
        </Alert>
      )}

      {applyWarning && <Alert variant="warning">{applyWarning}</Alert>}

      {multiStepApply && !manualApply && guideStep === "apply" && (
        <Alert variant="info">{multiStepApplyHint(applyUrl)}</Alert>
      )}

      {guideStep === "status" && (
        <div
          ref={statusSectionRef}
          id="update-status"
          className={`scroll-mt-24 transition-shadow duration-500 ${
            statusHighlight
              ? "rounded-2xl ring-2 ring-emerald-500 ring-offset-2"
              : ""
          }`}
        >
          <Card>
            <h2 className="mb-1 text-lg font-semibold">Update status</h2>
            {statusHighlight && (
              <p className="mb-3 text-sm text-emerald-700">
                Choose a status — e.g. <strong>submitted</strong> after you
                submit the application in the browser.
              </p>
            )}
            <div className="flex flex-wrap gap-2">
              {STATUS_OPTIONS.map((s) => (
                <Button
                  key={s}
                  variant={app.status === s ? "primary" : "secondary"}
                  onClick={() => setStatus(s)}
                >
                  {s.replace(/_/g, " ")}
                </Button>
              ))}
            </div>
          </Card>
        </div>
      )}
    </div>
  );
}
